### ISSUE TITLE
Have questions

### ISSUE THREAD

**Issue by ziceptor** [randombyte-developer/long-messages#1]
1. File missing config/long-messages.conf.
2. Need a team /lmsgs debug. Which will allow you to see in the console the command to run.

Nucleus allows me to see it https://gist.github.com/ziceptor/3b8fa09bab35ffbec1c9a9f757465e98
but I see in the team '+ '. The issue arose because of not the correct result command.

**Comment by randombyte-developer** [comment]
1. It'll generate after the first use of the default characters(plus sign or three dots).
I'll let it generate at server startup in the next release. 

2. You used the `/lmsgs` wrongly. The documentation doesn't make clear that when prepending `/lmsgs` you don't have to append a trigger character(here: the plus sign). I'll update the wiki. 
But the example is correct, see https://github.com/randombyte-developer/long-messages/wiki/Common-workflow#storing-a-command

**Comment by ziceptor** [comment]
So right? https://cloud.mail.ru/public/81KB/p3CXxtB3M Recognition error tags.

It seems to me that this format is more logical:

1. /lmsgs /command text
2. +text
3. +text

**Comment by ziceptor** [comment]
forge-1.11.2-13.20.0.2227-universal.jar
spongeforge-1.11.2-2227-6.0.0-BETA-2260.jar
long-messages-2.0.jar

**Comment by randombyte-developer** [comment]
The format evolved from the idea that you want to send a message but noticed at the end that you don't have enough space left, so you only append a + and hit enter.
I will add a config option to turn on trigger characters placed at the front of the message.

Regarding the screenshot you sent: you have probably used it wrongly.

**Comment by randombyte-developer** [comment]
https://ore.spongepowered.org/RandomByte/LongMessages/versions/2.0.1 , okay?

**Comment by ziceptor** [comment]
I'll check

**Comment by ziceptor** [comment]
https://cloud.mail.ru/public/CbQ2/TjHWRCxBq <-- Recognition error tags.
https://cloud.mail.ru/public/Gdsh/9A9U32Ujb <-- Discards part command. A resident is created with other products.
https://cloud.mail.ru/public/GiVW/9HaL3KDpN <-- '+' before slash (/lmsgs +/command): only send message

**Comment by ziceptor** [comment]
Strange, now I got it.

+/summon villager ~ ~1 ~ {Invulnerable:1,PersistenceRequired:1,CustomName:"Продавец",
+Offers:{Recipes:[{buy:{id:rotten_flesh,Count:40},sell:{id:golden_shovel,Count:1},maxUses:
+9999999},{buy:{id:bone,Count:15},sell:{id:golden_axe,Count:1},maxUses:9999999}]},
+Profession:4,Career:1,CareerLevel:1}

Perceived as a team. And created what you need.

**Comment by randombyte-developer** [comment]
What did you do differently than before? Do you think the docs are too complicated?

**Comment by ziceptor** [comment]
/lmsgs +/summon It was wrong. I misunderstood. Now well. Thank you!

**Comment by ziceptor** [comment]
Just wondering. Is it possible to display command input command interface of the command block?

**Comment by ziceptor** [comment]
Longer commands are usually written without of the chat. After just copied. If I had the ability to copy the whole team... would be great!

**Comment by ziceptor** [comment]
Sorry for bad English. If necessary, paraphrase.

**Comment by randombyte-developer** [comment]
I have to see if that's possible. #2
